services:
    avathar.bbguildeq2.installer:
        class: avathar\bbguildeq2\game\eq2_installer
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'

    avathar.bbguildeq2.provider:
        class: avathar\bbguildeq2\game\eq2_provider
        arguments:
            - '@avathar.bbguildeq2.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
